language: node_js
node_js:
  - "lts/*"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - chmod +x .travis/push.sh

install:
  - npm install -g yarn

script:
  - yarn
  - yarn crawler
  - yarn build

after_success:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then sh .travis/push.sh; else echo "Not cron. Skipping push to GitHub"; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist
  keep_history: true
  on:
    branch: master
